### ISSUE TITLE
ThreadedHistory not defined

### ISSUE THREAD

**Issue by chrismwendt** [litxio/ptghci#11]
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/chrismwendt/github.com/litxio/ptghci/.stack-work/install/x86_64-osx/lts-13.17/8.6.4/share/x86_64-osx-ghc-8.6.4/ptghci-0.1.0.0/pybits/ptghci/app.py", line 29, in __init__
    self.history = ThreadedHistory(FileHistory(
NameError: name 'ThreadedHistory' is not defined
```

Seems to be caused by https://github.com/litxio/ptghci/commit/957fc8102f9598709ef7097d66ddde0d103deffb

Originally accidentally discovered in https://github.com/litxio/ptghci/issues/10

**Comment by RichardWarfield** [comment]
That's what I get for rushing a fix before bed time.  This should be fixed now.  Thanks for reporting it.
