### ISSUE TITLE
Python program can't find dependencies installed in a `pyenv` environment

### ISSUE THREAD

**Issue by augustawind** [litxio/ptghci#23]
After installing ptghci per the instructions in the README, when I ran the app I got this error:

```console
λ ptghci(master)* -> ptghci
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/dtr/src/ptghci/.stack-work/install/x86_64-osx/dc50670124a5eb77c08d5e01d3e00bb5b37b560f6954cf18fb745392804b1d92/8.6.5/share/x86_64-osx-ghc-8.6.5/ptghci-0.1.0.0/pybits/ptghci/app.py", line 5, in <module>
    import colors
ModuleNotFoundError: No module named 'colors'
```

...indicating that dependencies were not installed, which they were:

```console
λ ptghci(master)* -> pip install -r pybits/requirements.txt
Requirement already satisfied: ansicolors>=1.1.8 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 2)) (1.1.8)
Requirement already satisfied: prompt-toolkit>=2.0.9 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 3)) (3.0.5)
Requirement already satisfied: pygments>=2.3.1 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 4)) (2.6.1)
Requirement already satisfied: pygtrie>=2.3 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 5)) (2.3.3)
Requirement already satisfied: pyyaml>=5.1 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 6)) (5.3.1)
Requirement already satisfied: pyzmq>=15.2.0 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 7)) (19.0.1)
Requirement already satisfied: six>=1.12.0 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 8)) (1.12.0)
Requirement already satisfied: wcwidth>=0.1.7 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 9)) (0.1.9)
Requirement already satisfied: zmq>=0.0.0 in /Users/dtr/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from -r pybits/requirements.txt (line 10)) (0.0.0)
```

I did some trial-and-error and found that the problem had to do with [pyenv](https://github.com/pyenv/pyenv), which shims the Python executable to allow installing and switching between multiple Python versions. For some reason ptghci isn't able to find the dependencies when installed in a pyenv environment (perhaps because it itself somehow subverts pyenv and is installed in the system Python?). 

I was able to workaround this by switching to the system Python installation and installing the requirements there:

```console
λ ptghci(master)* -> pyenv shell system
λ ptghci(master)* -> pip install -r pybits/requirements.txt
Collecting ansicolors>=1.1.8 (from -r pybits/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/53/18/a56e2fe47b259bb52201093a3a9d4a32014f9d85071ad07e9d60600890ca/ansicolors-1.1.8-py2.py3-none-any.whl
Collecting prompt-toolkit>=2.0.9 (from -r pybits/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/e4/a7/81b39aa50e9284fe2cb21cc7fb7de7817b224172d42793fd57451d38842b/prompt_toolkit-3.0.5-py3-none-any.whl
Collecting pygments>=2.3.1 (from -r pybits/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
Collecting pygtrie>=2.3 (from -r pybits/requirements.txt (line 5))
Collecting pyyaml>=5.1 (from -r pybits/requirements.txt (line 6))
Collecting pyzmq>=15.2.0 (from -r pybits/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/a7/8f/a823397e06379907af81009aca877837968f57d2864232b1e43eba77cb58/pyzmq-19.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
Requirement already satisfied: six>=1.12.0 in /usr/local/Cellar/protobuf/3.7.1/libexec/lib/python3.7/site-packages (from -r pybits/requirements.txt (line 8)) (1.12.0)
Collecting wcwidth>=0.1.7 (from -r pybits/requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting zmq>=0.0.0 (from -r pybits/requirements.txt (line 10))
Installing collected packages: ansicolors, wcwidth, prompt-toolkit, pygments, pygtrie, pyyaml, pyzmq, zmq
Successfully installed ansicolors-1.1.8 prompt-toolkit-3.0.5 pygments-2.6.1 pygtrie-2.3.3 pyyaml-5.3.1 pyzmq-19.0.1 wcwidth-0.1.9 zmq-0.0.0
```

After that I could switch back to normal (non-system) pyenv behavior and run ptghci with no issues:

```console
λ ptghci(master)* -> pyenv shell 3.8.0
λ ptghci(master)* -> ptghci
ptGHCi running GHCi version 8.6.5
```

**Comment by RichardWarfield** [comment]
Sorry for the late reply.  

I think the way you've handled this - by switching to the global Python install and installing the requirements there -- is probably the only feasible approach.  

pyenv only affects the python executable that runs when you type `python` on the command line, but ptghci doesn't use the python executable -- it instead embeds libpython (which stack/cabal find via pkg-config).
