### ISSUE TITLE
Issue when installed in MacOS - macOS High Sierra - 10.13.2

### ISSUE THREAD

**Issue by svraghavan** [litxio/ptghci#4]
**Engine stopping**
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/scratch/vrdev/haskell-proj/ptghci/.stack-work/install/x86_64-osx/lts-13.17/8.6.4/share/x86_64-osx-ghc-8.6.4/ptghci-0.1.0.0/pybits/ptghci/app.py", line 5, in <module>
    import colors
ModuleNotFoundError: No module named 'colors'
ptghci: getProcessGroupIDOf: does not exist (No such process)

I did check and colors module is already available

**Comment by o1lo01ol1o** [comment]
I got this error; `pkg-config` had linked the wrong `python3`.  Exporting the correct path (#3) fixed it.

**Comment by RichardWarfield** [comment]
I wasn't able to reproduce this on MacOS, so will close this on the assumption that o1lo01ol1o's comment points to the solution.  Feel free to re-open if that didn't resolve the issue.
